"""migration

Revision ID: 10ef3b471668
Revises: b9cc46cb088b
Create Date: 2025-05-16 17:12:05.438729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ef3b471668'
down_revision = 'b9cc46cb088b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('task_type', sa.String(length=32), nullable=True))
        batch_op.alter_column('ended_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('productivity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('productivity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ended_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('task_type')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
