"""added productivity, mood, and subject name to sessions db

Revision ID: b9cc46cb088b
Revises: 7ab2e580b0b3
Create Date: 2025-05-15 15:19:47.386509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cc46cb088b'
down_revision = '7ab2e580b0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productivity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('mood')
        batch_op.drop_column('productivity')

    # ### end Alembic commands ###
